# Generated by Django 5.1 on 2024-08-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litfic',
            name='litfiction',
        ),
        migrations.RemoveField(
            model_name='memoir',
            name='memoir',
        ),
        migrations.RemoveField(
            model_name='random',
            name='random',
        ),
        migrations.RemoveField(
            model_name='romance',
            name='romance',
        ),
        migrations.RemoveField(
            model_name='thriller',
            name='thriller',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='genre',
        ),
        migrations.AddField(
            model_name='category',
            name='comment',
            field=models.TextField(default='comment'),
        ),
        migrations.AddField(
            model_name='category',
            name='genre',
            field=models.CharField(default='genre', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='review'),
        ),
        migrations.AlterField(
            model_name='category',
            name='synopsis',
            field=models.TextField(default='synopsis'),
        ),
        migrations.DeleteModel(
            name='Horror',
        ),
        migrations.DeleteModel(
            name='Litfic',
        ),
        migrations.DeleteModel(
            name='Memoir',
        ),
        migrations.DeleteModel(
            name='Random',
        ),
        migrations.DeleteModel(
            name='Romance',
        ),
        migrations.DeleteModel(
            name='Thriller',
        ),
    ]
